### ISSUE TITLE
If couldn't connect to server result is 0

### ISSUE THREAD

**Issue by rrzaripov** [michaelversus/insomnia-plugin-multiple-requests#1]
First of, thank you for useful plugin! The only two things I think can improve it.

1. Now if we couldn't connect to server status is 0. Maybe mark it as `Error` as in primary window?

![image](https://user-images.githubusercontent.com/6154870/75076744-0501d580-5512-11ea-8ca3-b745e2d10e4b.png)

2. If it is possible to use badges as in primary window, it would be great for visualisation of results.
Thank you again! 

![image](https://user-images.githubusercontent.com/6154870/75077131-ee0fb300-5512-11ea-9c9a-83b1e8c6b862.png)
![image](https://user-images.githubusercontent.com/6154870/75077170-0bdd1800-5513-11ea-950c-39a2f53ab20d.png)

**Comment by TiagoCunhaF** [comment]
rrzaripov, I add bages styles and two columns in result modal, see:

![image](https://user-images.githubusercontent.com/26610915/83676673-6e818d80-a5b1-11ea-8e1c-56405a4ea08d.png)
